### ISSUE TITLE
Poster for Rust for Undergrads

### ISSUE THREAD

**Issue by biswajeet619** [swechaFSMI/Rust-for-undergrads#4]
Hey guys can anyone make a poster of an event known as "Rust for undergrads" giving a short description about Rust programming language. The venue is Swecha office, Gachibowli, Hyderabad.

**Comment by sanjitschouhan** [comment]
Moved to Open Design Repository [issue #179](https://github.com/mozilla/OpenDesign/issues/179)

**Comment by barrosgeraldo** [comment]
Hey folks, posters are available now here: https://github.com/mozilla/OpenDesign/issues/179
